version: "3.5"

services:
  api:
    build: ./api
    container_name: omnia-ml_api
    networks:
      - omnia-ml
    ports:
      - "8080:8080"

  # use https://github.com/quay/jwtproxy when issue solved - https://github.com/quay/jwtproxy/pull/119
  # proxy:
  #   image: quay.io/coreos/jwtproxy
  #   container_name: omnia-ml_proxy
  #   volumes:
  #     - type: bind
  #       source: ./proxy/verifier.yaml
  #       target: /config/config.yaml
  #   networks:
  #     - omnia-ml
  #   ports:
  #     - "8081:8081"

  jwt-auth:
    image: keaaa/jwt-auth
    container_name: omnia-ml_jwt_auth
    environment:
      - API_RESOURCE_ID=${API_RESOURCE_ID}
      - PUBLIC_KEYS_ENDPOINT=https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/discovery/v2.0/keys
    networks:
      - omnia-ml
    ports:
      - "8083:8080"

  swagger:
    image: swaggerapi/swagger-ui
    container_name: omnia-ml_swagger
    environment: 
      - URL=/swagger.json
    networks:
      - omnia-ml
    ports:
      - "8082:8080"  

  proxy:
    image: bitnami/nginx:latest
    container_name: omnia-ml_proxy
    volumes:
      - type: bind
        source: ./proxy/server.conf
        target: /opt/bitnami/nginx/conf/server_blocks/server.conf
    networks:
      - omnia-ml
    ports:
      - "8081:8080"

  auth:
    image: quay.io/pusher/oauth2_proxy:v4.0.0
    container_name: omnia-ml_auth
    environment:
      # See the `radixconfig.yaml` file for a description of these settings
      - OAUTH2_PROXY_CLIENT_ID=5687b237-eda3-4ec3-a2a1-023e85a2bd84
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_REFRESH=60m
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_COOKIE_SECURE=false # only for development
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_HTTP_ADDRESS=http://:8000
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
      - OAUTH2_PROXY_PASS_BASIC_AUTH=false
      - OAUTH2_PROXY_PASS_USER_HEADERS=false
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:8000/oauth2/callback
      - OAUTH2_PROXY_REDIS_CONNECTION_URL=redis://auth-state:6379
      - OAUTH2_PROXY_SCOPE=openid profile ${API_RESOURCE_ID}/user_impersonation email
      - OAUTH2_PROXY_SESSION_STORE_TYPE=redis
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_UPSTREAMS=http://proxy:8080
    networks:
      - omnia-ml
    ports:
      - "8000:8000" # In prod, this is served on port 443

  auth-state:
    image: redis:5-alpine
    container_name: omnia-ml_auth_state
    networks:
      - omnia-ml
    ports:
      - "6379:6379"

networks:
  omnia-ml:
    name: omnia-ml
